packages:
  - apps/*
  - packages/*

storeDir: .pnpm-store
cacheDir: .pnpm-cache
stateDir: .pnpm-state

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@conventional-changelog/template@1.4.0'
  - conventional-changelog-conventionalcommits@10.4.0
