/var/log/uo-request-generator/technical.log {
    daily
    ifempty
    rotate 4
    maxage 5
    missingok
    create 0600 syslog syslog
    sharedscripts
    postrotate
        systemctl kill --signal=HUP rsyslog.service
    endscript
}
