#!/bin/sh
set -eu

[ "$#" -eq 0 ] || exit 2

exec /usr/bin/flock -w 60 /var/log/uo-request-generator/.rotation.lock \
    /usr/sbin/logrotate -s /var/log/uo-request-generator/.logrotate.state \
    /etc/uo-request-generator/technical-logrotate.conf
