template(name="uo_technical_line" type="string" string="%timegenerated:::date-rfc3339% %syslogtag% %msg%\n")
$outchannel uo_technical,/var/log/uo-request-generator/technical.log,10485760,/usr/local/libexec/uo-request-generator/rotate-technical-logs force

ruleset(name="uo_request_generator_technical") {
  *.* :omfile:$uo_technical;uo_technical_line
  stop
}

input(
  type="imuxsock"
  socket="/var/log/uo-request-generator/technical.sock"
  ruleset="uo_request_generator_technical"
)
