template(name="uo_technical_line" type="string" string="%timegenerated:::date-rfc3339% %syslogtag% %msg%\n")

ruleset(name="uo_request_generator_technical") {
  action(
    type="omfile"
    file="/var/log/uo-request-generator/technical.log"
    fileCreateMode="0600"
    fileOwner="syslog"
    fileGroup="syslog"
    template="uo_technical_line"
  )
  stop
}

input(
  type="imuxsock"
  socket="/var/log/uo-request-generator/technical.sock"
  ruleset="uo_request_generator_technical"
)
